services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openmusic-api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    environment:
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
      PGHOST: '${PGHOST}'
      PGPORT: '${PGPORT}'
      PGDATABASE: '${PGDATABASE}'
      REDIS_SERVER: '${REDIS_SERVER}'
    depends_on:
      - postgres-db
      - rabbitmq
      - redis
    command: >
      sh -c "
        sleep 10 &&
        npm ci &&
        npm run migrate:up &&
        npm run start-dev"
    networks:
      - app-network

  postgres-db:
    image: postgres:15.10
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${PGDATABASE}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network
    command:
      ['postgres', '-c', 'log_statement=all', '-c', 'log_destination=stderr']

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    user: rabbitmq
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      - '${RABBITMQ_MANAGEMENT_UI_PORT}:${RABBITMQ_MANAGEMENT_UI_PORT}'
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_USERNAME}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD}'
      RABBITMQ_ERLANG_COOKIE: '${RABBITMQ_ERLANG_COOKIE}'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq:rw
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    ports:
      - '9000:9000' # API port
      - '9001:9001' # Console port
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres-data:
  rabbitmq-data:
  minio-data:
  redis-data:

networks:
  app-network:
    driver: bridge
