services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openmusic-api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '${PORT}:${PORT}'
    environment:
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
      PGHOST: '${PGHOST}'
      PGPORT: '${PGPORT}'
      PGDATABASE: '${PGDATABASE}'
    depends_on:
      - database
    command: >
      sh -c "npm install && npm run migrate:up && npm run start"

  database:
    image: postgres:15.10
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${PGDATABASE}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-data:
