services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openmusic-api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    environment:
      PGUSER: '${PGUSER}'
      PGPASSWORD: '${PGPASSWORD}'
      PGHOST: '${PGHOST}'
      PGPORT: '${PGPORT}'
      PGDATABASE: '${PGDATABASE}'
    depends_on:
      - postgres-db
      - rabbitmq
    command: >
      sh -c "
        sleep 10 &&
        npm ci &&
        npm run migrate:up &&
        npm run start-dev"
    networks:
      - app-network

  postgres-db:
    image: postgres:15.10
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: '${PGUSER}'
      POSTGRES_PASSWORD: '${PGPASSWORD}'
      POSTGRES_DB: '${PGDATABASE}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network
    command:
      ['postgres', '-c', 'log_statement=all', '-c', 'log_destination=stderr']

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    user: rabbitmq
    ports:
      - '${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      - '${RABBITMQ_MANAGEMENT_UI_PORT}:${RABBITMQ_MANAGEMENT_UI_PORT}'
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_USERNAME}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_PASSWORD}'
      RABBITMQ_ERLANG_COOKIE: '${RABBITMQ_ERLANG_COOKIE}'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq:rw
    networks:
      - app-network

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  app-network:
    driver: bridge
